name: Publish crate
on:
  create:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to cargo
      run: cargo login $CARGO_TOKEN
    - name: Publish package
      run: cargo publish
