name: Publish crate

on:
  create:
    tags: [ "v*" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish package
      run: 'cargo login $CARGO_TOKEN && cargo publish'
